<?php

function fixed(string $key, string $label, string $fieldType = 'text', bool $required = false): array
{
    return [
        'key' => $key,
        'label' => $label,
        'field_type' => $fieldType,
        'options' => null,
        'is_required' => $required,
        'is_hidden' => false,
    ];
}

return [
    'modules' => [
        'accounts-store' => ['columns' => [
            fixed('merchantName', 'Merchant Name', 'text', true),
            fixed('storeLocationName', 'Store Location Name'),
            fixed('storeAddress', 'Store Address', 'textarea'),
            fixed('storeManager', 'Store Manager'),
            fixed('storeEmail', 'Store Email', 'email'),
            fixed('storeContactNumber', 'Store Contact #'),
            fixed('bank', 'Bank'),
            fixed('accountName', 'Account Name'),
            fixed('accountNumber', 'Account #', 'password'),
            fixed('status', 'Status', 'status', true),
            fixed('notes', 'Notes', 'notes'),
            fixed('lastUpdated', 'Last Updated', 'date'),
            fixed('updatedBy', 'Updated By'),
        ]],
        'accounts-pldt' => ['columns' => [
            fixed('company', 'Company'),
            fixed('branch', 'Branch'),
            fixed('status', 'Status', 'status', true),
            fixed('remarks', 'Remarks', 'textarea'),
            fixed('check', 'Check'),
            fixed('companyAccount', 'Company Account'),
            fixed('accountNumber', 'Account Number', 'password'),
            fixed('notes', 'Notes', 'notes'),
            fixed('lastUpdated', 'Last Updated', 'date'),
            fixed('updatedBy', 'Updated By'),
        ]],
        'accounts-links' => ['columns' => [
            fixed('department', 'Department'),
            fixed('email', 'Email', 'email'),
            fixed('username', 'Username'),
            fixed('password', 'Password', 'password'),
            fixed('link', 'Link'),
            fixed('status', 'Status', 'status', true),
            fixed('notes', 'Notes', 'notes'),
            fixed('lastUpdated', 'Last Updated', 'date'),
            fixed('updatedBy', 'Updated By'),
        ]],
        'emails' => ['columns' => [
            fixed('emailsType', 'Emails Type', 'select', true),
            fixed('emailAccount', 'Email Account', 'email', true),
            fixed('password', 'Password', 'password'),
            fixed('department', 'Department'),
            fixed('personUsed', 'Person Used'),
            fixed('purpose', 'Purpose', 'textarea'),
            fixed('recoveryEmail', 'Recovery Email', 'email'),
            fixed('recoveryNumberVerification', 'Recovery Number & Verification', 'textarea'),
        ]],
        'ip-addresses' => ['columns' => [
            fixed('location', 'Location', 'text', true),
            fixed('deviceType', 'Device Type', 'select', true),
            fixed('name', 'Name', 'text', true),
            fixed('department', 'Department', 'text', true),
            fixed('deviceName', 'Device Name', 'text', true),
            fixed('macAddress', 'MAC Address', 'text', true),
            fixed('ipAddress', 'IP Address', 'text', true),
            fixed('status', 'Status', 'status', true),
            fixed('notes', 'Notes', 'notes'),
            fixed('lastUpdated', 'Last Updated', 'date'),
            fixed('updatedBy', 'Updated By'),
        ]],
        'cctv-avada-center' => ['columns' => [
            fixed('floorName', 'Floor Name'),
            fixed('cameraNumber', 'Camera #'),
            fixed('cameraName', 'Camera Name'),
            fixed('username', 'Username'),
            fixed('password', 'Password', 'password'),
            fixed('nvrIp', 'NVR IP'),
            fixed('cameraIp', 'Camera IP'),
            fixed('status', 'Status', 'status'),
        ]],
        'cctv-boutique' => ['columns' => [
            fixed('branch', 'Branch'),
            fixed('brand', 'Brand'),
            fixed('workingCameras', 'Working Cameras'),
            fixed('serial', 'Serial'),
            fixed('username', 'Username'),
            fixed('password', 'Password', 'password'),
            fixed('webIp', 'Web IP'),
            fixed('storage', 'Storage'),
            fixed('status', 'Status', 'status'),
        ]],
        'cctv-warehouse-online' => ['columns' => [
            fixed('branch', 'Branch'),
            fixed('brand', 'Brand'),
            fixed('model', 'Model'),
            fixed('serial', 'Serial'),
            fixed('username', 'Username'),
            fixed('password', 'Password', 'password'),
            fixed('webIp', 'Web IP'),
            fixed('storage', 'Storage'),
            fixed('status', 'Status', 'status'),
        ]],
        'wifi-data' => ['columns' => [
            fixed('location', 'Location'),
            fixed('areaFloor', 'Area / Floor'),
            fixed('ispProvider', 'ISP Provider'),
            fixed('routerBrand', 'Router Brand'),
            fixed('routerModel', 'Router Model'),
            fixed('portalUsername', 'Portal Username'),
            fixed('portalPassword', 'Portal Password', 'password'),
            fixed('ssidName', 'SSID Name'),
            fixed('wifiPassword', 'WiFi Password', 'password'),
            fixed('wanIp', 'WAN IP'),
            fixed('gatewayIp', 'Gateway IP'),
            fixed('lanIp', 'LAN IP'),
            fixed('deviceIp', 'Device IP'),
            fixed('deviceType', 'Device Type'),
            fixed('connectionType', 'Connection Type'),
            fixed('status', 'Status', 'status'),
            fixed('notes', 'Notes', 'notes'),
        ]],
        'remote-desktops' => ['columns' => [
            fixed('type', 'Type'),
            fixed('location', 'Location'),
            fixed('name', 'Name'),
            fixed('department', 'Department'),
            fixed('ipAddress', 'IP Address'),
            fixed('terminalNumber', 'Terminal #'),
            fixed('computerName', 'Computer Name'),
            fixed('branch', 'Branch'),
            fixed('posDateUsed', 'POS Date Used', 'date'),
            fixed('anydeskId', 'AnyDesk ID'),
            fixed('password', 'Password', 'password'),
            fixed('teamViewer', 'TeamViewer'),
            fixed('status', 'Status', 'status'),
            fixed('notes', 'Notes', 'notes'),
        ]],
        'pos-hookups' => ['columns' => [
            fixed('branch', 'Branch'),
            fixed('contractNumber', 'Contract #'),
            fixed('code', 'Code'),
            fixed('ipAddress', 'IP Address'),
            fixed('subnetMask', 'Subnet Mask'),
            fixed('gateway', 'Gateway'),
            fixed('mallServerIp', 'Mall Server IP'),
            fixed('ssidUsername', 'SSID / Username'),
            fixed('password', 'Password', 'password'),
            fixed('salesPath', 'Sales Path'),
            fixed('status', 'Status', 'status'),
            fixed('notes', 'Notes', 'notes'),
        ]],
        'social-media-accounts' => ['columns' => [
            fixed('type', 'Type'),
            fixed('email', 'Email', 'email'),
            fixed('password', 'Password', 'password'),
            fixed('department', 'Department'),
            fixed('personUsed', 'Person Used'),
            fixed('shopName', 'Shop Name'),
            fixed('sellerIdShopCode', 'Seller ID / Shop Code'),
            fixed('phoneNumber', 'Phone No.'),
            fixed('status', 'Status', 'status'),
            fixed('notes', 'Notes', 'notes'),
        ]],
        'users' => ['columns' => [
            fixed('name', 'User'),
            fixed('username', 'Username'),
            fixed('role', 'Role', 'status'),
            fixed('status', 'Status', 'status'),
            fixed('lastActive', 'Last Active', 'date'),
        ]],
    ],
];
