import type { ComponentProps } from 'react'
import {
  Activity,
  AlertTriangle,
  ArrowUpRight,
  AtSign,
  BadgeDollarSign,
  Banknote,
  Bell,
  Building2,
  Cable,
  Camera,
  CameraOff,
  ChartSpline,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Clock3,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileSpreadsheet,
  Filter,
  FolderOpen,
  Gauge,
  Globe2,
  HardDrive,
  Hash,
  History,
  ImageUp,
  Info,
  KeyRound,
  Laptop,
  LayoutDashboard,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Mail,
  MailCheck,
  MailWarning,
  MapPin,
  Menu,
  Monitor,
  MonitorCog,
  Moon,
  MoreHorizontal,
  Network,
  Palette,
  PanelLeft,
  Pencil,
  Phone,
  PhoneOff,
  Plus,
  QrCode,
  RadioTower,
  Receipt,
  RotateCcw,
  Router,
  Save,
  Search,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Signal,
  SlidersHorizontal,
  Store,
  Sun,
  SunMoon,
  Trash2,
  Upload,
  User,
  UserRound,
  UserRoundCheck,
  UserRoundX,
  Users,
  UsersRound,
  Wallet,
  Wifi,
  WifiOff,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react'
import { cn } from './utils'

export type SystemIconName = keyof typeof systemIcons
export type IconSize = keyof typeof iconSizes
export type { LucideIcon }

export const iconSizes = {
  sidebar: 18,
  table: 16,
  header: 20,
  summary: 22,
  dropdown: 16,
  modal: 18,
  button: 16,
  inline: 14,
} as const

export const iconStrokeWidth = 2

export const systemIcons = {
  dashboard: LayoutDashboard,
  internetInfo: Globe2,
  internetGraph: ChartSpline,
  wifiData: Wifi,
  ipAddressing: Network,
  remote: Monitor,
  remoteDesktop: MonitorCog,
  posHookup: Receipt,
  accounts: Wallet,
  emails: Mail,
  socialMedia: Share2,
  cctv: Camera,
  boutique: Store,
  users: Users,
  rolesPermissions: ShieldCheck,
  settings: Settings,
  profile: User,
  notifications: Bell,
  logout: LogOut,
  search: Search,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  save: Save,
  upload: Upload,
  download: Download,
  import: FileSpreadsheet,
  view: Eye,
  hide: EyeOff,
  copy: Copy,
  filter: Filter,
  history: History,
  open: ExternalLink,
  test: RadioTower,
  close: X,
  success: CheckCircle2,
  warning: AlertTriangle,
  info: Info,
  error: XCircle,
  security: ShieldCheck,
} as const

type SystemIconProps = Omit<ComponentProps<LucideIcon>, 'size' | 'strokeWidth'> & {
  name: SystemIconName
  size?: IconSize | number
}

export function SystemIcon({ className, name, size = 'inline', ...props }: SystemIconProps) {
  const Icon = systemIcons[name]
  const resolvedSize = typeof size === 'number' ? size : iconSizes[size]

  return (
    <Icon
      aria-hidden="true"
      className={cn('system-icon', className)}
      size={resolvedSize}
      strokeWidth={iconStrokeWidth}
      {...props}
    />
  )
}

export {
  Activity,
  AlertTriangle,
  ArrowUpRight,
  AtSign,
  BadgeDollarSign,
  Banknote,
  Bell,
  Building2,
  Cable,
  Camera,
  CameraOff,
  ChartSpline,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Clock3,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileSpreadsheet,
  Filter,
  FolderOpen,
  Gauge,
  Globe2,
  HardDrive,
  Hash,
  History,
  ImageUp,
  Info,
  KeyRound,
  Laptop,
  LayoutDashboard,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Mail,
  MailCheck,
  MailWarning,
  MapPin,
  Menu,
  Monitor,
  MonitorCog,
  Moon,
  MoreHorizontal,
  Network,
  Palette,
  PanelLeft,
  Pencil,
  Phone,
  PhoneOff,
  Plus,
  QrCode,
  RadioTower,
  Receipt,
  RotateCcw,
  Router,
  Save,
  Search,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Signal,
  SlidersHorizontal,
  Store,
  Sun,
  SunMoon,
  Trash2,
  Upload,
  User,
  UserRound,
  UserRoundCheck,
  UserRoundX,
  Users,
  UsersRound,
  Wallet,
  Wifi,
  WifiOff,
  X,
  XCircle,
}
